# Site settings
title: Discovery Works
description: Discovery Works is a product development studio exploring how humans and computers work together.
baseurl: ""
url: "https://discovery.works"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  services:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - MEMORY-BANK/

# Site navigation
nav_links:
  # - title: Services
  #   url: /services/
  # - title: About
  #   url: /about/
  # - title: Journal
  #   url: /journal/
  # - title: Get Started
  #   url: /get-started/
