# Site settings
title: Discovery Works
description: Straightforward, honest, financial advice. We are a financial advisory group that focuses on investment planning, asset management, and overall financial literacy.
baseurl: ""
url: "https://discovery.works"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  services:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - MEMORY-BANK/

# Site navigation
nav_links:
  - title: Services
    url: /services/
  - title: About
    url: /about/
  - title: Journal
    url: /journal/
  - title: Get Started
    url: /get-started/